// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package router

import (
	"radiusbilling/api"
	"radiusbilling/internal/core"
	"radiusbilling/repo"
	"radiusbilling/service"
)

// Injectors from wire.go:

func initRoleAPI(engine *core.Engine) api.RoleAPI {
	roleRepo := repo.ProvideRoleRepo(engine)
	roleServ := service.ProvideRoleService(roleRepo)
	roleAPI := api.ProvideRoleAPI(roleServ)
	return roleAPI
}

func initUserAPI(engine *core.Engine) api.UserAPI {
	userRepo := repo.ProvideUserRepo(engine)
	userServ := service.ProvideUserService(userRepo)
	userAPI := api.ProvideUserAPI(userServ)
	return userAPI
}
