// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package router

import (
	"sigmamono/api"
	"sigmamono/internal/core"
	"sigmamono/repo"
	"sigmamono/service"
)

// Injectors from wire.go:

func initRoleAPI(engine *core.Engine) api.RoleAPI {
	roleRepo := repo.ProvideRoleRepo(engine)
	roleServ := service.ProvideRoleService(roleRepo)
	roleAPI := api.ProvideRoleAPI(roleServ)
	return roleAPI
}

func initUserAPI(engine *core.Engine) api.UserAPI {
	userRepo := repo.ProvideUserRepo(engine)
	userServ := service.ProvideUserService(userRepo)
	userAPI := api.ProvideUserAPI(userServ)
	return userAPI
}

func initCompanyAPI(e *core.Engine) api.CompanyAPI {
	companyRepo := repo.ProvideCompanyRepo(e)
	companyServ := service.ProvideCompanyService(companyRepo)
	companyAPI := api.ProvideCompanyAPI(companyServ)
	return companyAPI
}
