// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package router

import (
	"sigmamono/api"
	"sigmamono/internal/core"
	"sigmamono/repo"
	"sigmamono/service"
)

// Injectors from wire.go:

func initRoleAPI(e *core.Engine) api.RoleAPI {
	roleRepo := repo.ProvideRoleRepo(e)
	roleServ := service.ProvideRoleService(roleRepo)
	roleAPI := api.ProvideRoleAPI(roleServ)
	return roleAPI
}

func initUserAPI(engine *core.Engine) api.UserAPI {
	userRepo := repo.ProvideUserRepo(engine)
	userServ := service.ProvideUserService(userRepo)
	userAPI := api.ProvideUserAPI(userServ)
	return userAPI
}

func initAccountAPI(e *core.Engine) api.AccountAPI {
	accountRepo := repo.ProvideAccountRepo(e)
	accountServ := service.ProvideAccountService(accountRepo)
	accountAPI := api.ProvideAccountAPI(accountServ)
	return accountAPI
}
