// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package determine

import (
	"sigmamono/api"
	"sigmamono/internal/core"
	"sigmamono/repo"
	"sigmamono/service"
)

// Injectors from wire.go:

func initCompanyAPI(e *core.Engine) api.CompanyAPI {
	companyRepo := repo.ProvideCompanyRepo(e)
	companyServ := service.ProvideCompanyService(companyRepo)
	companyAPI := api.ProvideCompanyAPI(companyServ)
	return companyAPI
}

func initNodeAPI(e *core.Engine) api.NodeAPI {
	nodeRepo := repo.ProvideNodeRepo(e)
	nodeServ := service.ProvideNodeService(nodeRepo)
	nodeAPI := api.ProvideNodeAPI(nodeServ)
	return nodeAPI
}
