// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package determine

import (
	"sigmamono/api"
	"sigmamono/internal/core"
	"sigmamono/repo"
	"sigmamono/service"
)

// Injectors from wire.go:

func initVersionAPI(e *core.Engine) api.VersionAPI {
	versionRepo := repo.ProvideVersionRepo(e)
	versionServ := service.ProvideVersionService(versionRepo)
	versionAPI := api.ProvideVersionAPI(versionServ)
	return versionAPI
}

func initLicenseAPI(e *core.Engine) api.LicenseAPI {
	licenseServ := service.ProvideLicenseService(e)
	licenseAPI := api.ProvideLicenseAPI(licenseServ)
	return licenseAPI
}

func initRegisterAPI(e *core.Engine) api.RegisterAPI {
	registerServ := service.ProvideRegisterService(e)
	registerAPI := api.ProvideRegisterAPI(registerServ)
	return registerAPI
}

func initCompanyAPI(e *core.Engine) api.CompanyAPI {
	companyRepo := repo.ProvideCompanyRepo(e)
	companyServ := service.ProvideCompanyService(companyRepo)
	companyAPI := api.ProvideCompanyAPI(companyServ)
	return companyAPI
}

func initNodeAPI(e *core.Engine) api.NodeAPI {
	nodeRepo := repo.ProvideNodeRepo(e)
	nodeServ := service.ProvideNodeService(nodeRepo)
	nodeAPI := api.ProvideNodeAPI(nodeServ)
	return nodeAPI
}
