// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package determine

import (
	"sigmamono/api"
	"sigmamono/internal/core"
	"sigmamono/repo"
	"sigmamono/service"
)

// Injectors from wire.go:

func initStationAPI(e *core.Engine) api.StationAPI {
	stationRepo := repo.ProvideStationRepo(e)
	stationServ := service.ProvideStationService(stationRepo)
	stationAPI := api.ProvideStationAPI(stationServ)
	return stationAPI
}
