package term

// List of all errors in the app
const (
	Invalid_parameter_provided            = "invalid parameter provided"
	Accepted_values_for_status_are_v      = "accepted values for status are: %v"
	V_is_required                         = "%v is required"
	Name_at_least_be_5_character          = "name at least be 5 character"
	V_should_be_more_than_V_character     = "%v should be more than %v character"
	Username_or_password_is_wrong         = "username or password is wrong"
	You_dont_have_permission              = "you don't have permission"
	You_dont_have_permission_out_of_scope = "you don't have permission, out of scope!"
	Duplication_happened                  = "duplication happened"
	Accepted_values_for_type_are_v        = "accepted values for type are: %v"
	V_is_not_valid                        = "%v is not valid"
	Invalid_ID                            = "invalid id"
	Record_Not_Found                      = "record not found"
	V_deleted_successfully                = "%v deleted successfully"
	Route_not_found                       = "route not found"
	Token_is_required                     = "token is required"
	V_info                                = "%v info"
	Token_is_not_valid                    = "token is not valid"
	Error_in_nodes_url                    = "error in node's url"
	Error_in_nodes_form                   = "error in node's form"
	Error_in_versions_form                = "error in version's form"
	Error_in_companys_form                = "error in company's form"
	Error_in_users_form                   = "error in user's form"
	Error_in_login_form                   = "error in login form"
	Error_in_role_form                    = "error in role form"
	Error_in_url                          = "error in url"
	Error_in_casting                      = "error in casting"
	Error_in_saving_company               = "error in saving company"
	Error_in_saving_node                  = "error in saving node"
	Error_in_accounts_url                 = "error in account's url"
	Error_in_accounts_form                = "error in account's form"
	Accepted_values_are_v                 = "accepted values are: %v"
	Error_in_deleting_user                = "error in deleting user"
	Error_in_deleting_account             = "error in deleting account"
	Error_in_getting_user                 = "error in getting user"
	Email_is_not_valid                    = "email is not valid"
	Error_in_phones_url                   = "error in phone's url"
	Error_in_phones_form                  = "error in phone's form"
	Error_in_saving_user                  = "error in saving user"
	Error_in_saving_role                  = "error in saving role"
	Error_in_saving_bond                  = "error in saving bond"
	CompanyID_not_exist_in_context        = "company_id not exist in the context"
	NodeCode_not_exist_in_context         = "node_code not exist in the context"
	Validation_failed                     = "validation failed"
	Invalid_number                        = "invalid number"
	Range_is_v_to_v                       = "range is %v to %v"
	String_is_not_valid                   = "string is not valid"
	License_is_not_valid                  = "license is not valid"
	Company_license_has_been_expired      = "Company's license has been expired"
	Company_key_is_not_valid              = "Company key is not valid"
	CompanyID                             = "company_id"
	Internal_Error                        = "internal error"
	MachineID                             = "Machine ID"
)
